# Generated by Django 3.1.7 on 2021-03-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('post', '0001_initial'),
=======
        ("post", "0001_initial"),
>>>>>>> 8fb7be55e2233ebc996a9214624fb21724f8c6c6
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='post',
            name='files',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
=======
            model_name="post",
            name="files",
            field=models.FileField(null=True, upload_to="uploads/%Y/%m/%d/"),
>>>>>>> 8fb7be55e2233ebc996a9214624fb21724f8c6c6
        ),
    ]
